project:
  type: website

website:
  title: "Quarto Demo"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: param_quarto.qmd
        text: "Testing param for quarto"
      - href: README.html
        text: "README"

format:
  gfm:
    filters:
      - gfm-strip-disallowed



